=== Sondos11/-ITI_OpenSourceApplicationDevelopment/XML/lab 3/task1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="building_number"/>
				<xs:element ref="region"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="building_number">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="20"/>
				<xs:enumeration value="7"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexandria"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Sondos@gmail.com"/>
				<xs:enumeration value="mrwan@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Mrwan Ayman"/>
				<xs:enumeration value="Sondos Said"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
								<xs:enumeration value="work"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Bitash"/>
				<xs:enumeration value="syouf"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="madares"/>
				<xs:enumeration value="qaada"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:int">
			<xs:enumeration value="1045632763"/>
			<xs:enumeration value="1245678543"/>
			<xs:enumeration value="1265387443"/>
			<xs:enumeration value="1265442387"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Sondos11/-ITI_OpenSourceApplicationDevelopment/XML/lab 3/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="task2.xsl"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///F:/ITI/XML/labs/lab%203/task1.xsd">
	<employee>
		<name>Sondos Said</name>
		<phones>
			<phone type="home">01245678543</phone>
			<phone type="work">01045632763</phone>
		</phones>
		<addresses>
			<address>
				<street>qaada</street>
				<building_number>7</building_number>
				<region>Bitash</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>Sondos@gmail.com</email>
	</employee>
	<employee>
		<name>Mrwan Ayman</name>
		<phones>
			<phone type="mobile">01265387443</phone>
			<phone type="work">01265442387</phone>
		</phones>
		<addresses>
			<address>
				<street>madares</street>
				<building_number>20</building_number>
				<region>syouf</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>mrwan@gmail.com</email>
	</employee>
</employees>
